// Generated by scripts/prepare-media.py directly from original assets.
export const media = {
  "hero": {
    "width": 1600,
    "height": 1065,
    "widths": [
      320,
      640,
      960,
      1280,
      1600
    ]
  },
  "action": {
    "width": 1600,
    "height": 1200,
    "widths": [
      320,
      640,
      960,
      1280,
      1600
    ]
  },
  "action-detail": {
    "width": 1200,
    "height": 1600,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "experience": {
    "width": 1600,
    "height": 1200,
    "widths": [
      320,
      640,
      960,
      1280,
      1600
    ]
  },
  "origin": {
    "width": 1600,
    "height": 1200,
    "widths": [
      320,
      640,
      960,
      1280,
      1600
    ]
  },
  "claudia": {
    "width": 1080,
    "height": 800,
    "widths": [
      320,
      640,
      960,
      1080
    ]
  },
  "francisco": {
    "width": 1024,
    "height": 759,
    "widths": [
      320,
      640,
      960,
      1024
    ]
  },
  "luis": {
    "width": 1080,
    "height": 800,
    "widths": [
      320,
      640,
      960,
      1080
    ]
  },
  "book": {
    "width": 1200,
    "height": 1600,
    "widths": [
      320,
      640,
      960,
      1200
    ]
  },
  "microphone": {
    "width": 633,
    "height": 708,
    "widths": [
      320,
      633
    ]
  },
  "legal": {
    "width": 1600,
    "height": 1600,
    "widths": [
      320,
      640,
      960,
      1280,
      1600
    ]
  }
};
