"""Generate curated derivatives without writing to img. Requires Pillow and imageio-ffmpeg."""
from pathlib import Path
from PIL import Image, ImageOps
import sys, subprocess, shutil, json

sys.path.insert(0, str(Path('.tools/python').resolve()))
import imageio_ffmpeg

out = Path('public/media')
out.mkdir(parents=True, exist_ok=True)
selection = {
    'hero': 'WhatsApp Image 2026-10-02 at 09.04.27 (3).jpeg',
    'action': 'WhatsApp Image 2026-10-02 at 09.04.27.jpeg',
    'action-detail': 'WhatsApp Image 2026-10-02 at 09.04.27 (2).jpeg',
    'experience': 'WhatsApp Image 2026-10-02 at 09.04.26.jpeg',
    'origin': 'WhatsApp Image 2026-10-02 at 09.04.27 (4).jpeg',
    'claudia': 'Claudia-Trajano-1.webp',
    'francisco': 'Francisco-1024x759.webp',
    'luis': 'Flora.webp',
    'book': 'WhatsApp Image 2026-10-02 at 09.04.27 (1).jpeg',
    'microphone': 'WhatsApp Image 2026-10-02 at 09.04.28.jpeg',
    'legal': 'WhatsApp Image 2026-10-02 at 09.04.28 (2).jpeg',
}
manifest={}
for name,source in selection.items():
    im=ImageOps.exif_transpose(Image.open(Path('img')/source)).convert('RGB')
    widths=sorted(set([min(w,im.width) for w in [320,640,960,1280,1600]]))
    derivatives=[]
    for w in widths:
        destination=out/f'{name}-{w}.webp'
        preserved=w==im.width and Path(source).suffix.lower()=='.webp'
        if preserved:
            shutil.copy2(Path('img')/source,destination)
        else:
            copy=im.resize((w,round(im.height*w/im.width)),Image.Resampling.LANCZOS)
            copy.save(destination,quality=94,method=6)
        derivatives.append({'file':destination.name,'width':w,'height':round(im.height*w/im.width),'bytes':destination.stat().st_size,'quality':'original-copy' if preserved else 94,'format':'WEBP'})
    manifest[name]={'source':source,'sourceBytes':(Path('img')/source).stat().st_size,'sourceFormat':Image.open(Path('img')/source).format,'width':im.width,'height':im.height,'widths':widths,'derivatives':derivatives}
shutil.copy2('img/BTF-Branco-768x146.webp',out/'btf-logo.webp')
import runpy
runpy.run_path('scripts/prepare-videos.py', run_name='__main__')
# OpenGraph derivative uses real imagery and logo without an invented slogan baked in.
hero=ImageOps.fit(Image.open('img/'+selection['hero']).convert('RGB'),(1200,630),centering=(.5,.3))
overlay=Image.new('RGBA',hero.size,(16,44,57,100)); hero=Image.alpha_composite(hero.convert('RGBA'),overlay)
logo=Image.open('img/BTF-Branco-768x146.webp').convert('RGBA'); logo.thumbnail((420,80))
hero.alpha_composite(logo,(64,490)); hero.convert('RGB').save(out/'opengraph.jpg',quality=88)
Path('docs/audit/derivatives.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
Path('docs/audit/derivatives-v4.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
registry={name:{k:item[k] for k in ['width','height','widths']} for name,item in manifest.items()}
Path('src/content/media.ts').write_text('// Generated by scripts/prepare-media.py directly from original assets.\nexport const media = '+json.dumps(registry,indent=2)+';\n',encoding='utf-8')
# Remove only obsolete generated width variants owned by this pipeline, never originals.
current={derivative['file'] for item in manifest.values() for derivative in item['derivatives']}
for candidate in out.glob('*.webp'):
    asset,_,width=candidate.stem.rpartition('-')
    if asset in manifest and width.isdigit() and candidate.name not in current:
        if candidate.resolve().parent!=out.resolve():
            raise RuntimeError('Unexpected derivative path')
        candidate.unlink()
print('Curated images, logo, MP4, WebM, poster and OpenGraph generated. Originals preserved.')
